watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["komorebi_workspaces", "active_window"]
      center: ["clock"]
      right: ["wifi", "cpu", "memory", "battery"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{percent}% {time_remaining}"
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%y-%m-%d %H:%M}"
      label_alt: "{%y-%m-%d %H:%M}"
      timezones: ["Asia/Singapore"]

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "CPU: {info[percent][total]}"
      label_alt: "CPU: {info[percent][total]}"
      update_interval: 500

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "RAM: {virtual_mem_free}"
      label_alt: "RAM: {virtual_mem_free}"
      update_interval: 5000

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "W: {wifi_icon}"
      label_alt: "W: {wifi_icon}"
      update_interval: 5000
      wifi_icons:
        - "0%" # 0% strength (no wifi)
        - "25%" # 1-25% strength
        - "50%" # 26-50% strength
        - "75%" # 51-75% strength
        - "100%" # 76-100% strength. Alternate theming: \uf1eb
